---
- name: Download WordPress  
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no 
  become: true

- name: Extract WordPress  
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no 
  become: true

- name: Update default Apache site
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache
  become: true

- name: Download WP cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0755

- name: Create a new database with name 'wordpress'
  mysql_db:
    name: wordpress
    state: present
  become: true

- mysql_user:
    name: wordpress
    password: wp12345678
    priv: '*.*:ALL'
    state: present
  become: true

- file:
    path: ~/7digital/wordpress-install.sh
    mode: 0755

- name: Copy and Execute the script 
  script: ~/7digital/wordpress-install.sh

